stages:
  - build
  - dockerize
  - rollout

node-build-Develop:
  tags: 
    - master1
  image: node:14.17.2-alpine3.13
  stage: build
  artifacts:
    expire_in: 4h
    paths:
      - build/
  cache: 
   key: ${CI_JOB_I}
   paths:
    - node_modules/
    - public/
  script:
    - echo 'nameserver 8.8.8.8' > /etc/resolv.conf
    - npm version
    - CI=false yarn install
    - CI=false yarn run build:development
  only:
    - develop


dockerize-Develop:
  stage: dockerize
  tags: 
    - master1
  image: buildah/buildah
  dependencies:
    - node-build-Develop
  script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.vaslapp.com
    - buildah build-using-dockerfile -t registry.vaslapp.com/docker/ministers-dev:latest .
    - buildah push registry.vaslapp.com/docker/ministers-dev:latest
  only:
    - develop

    
rollout-Develop:
  stage: rollout
  tags:
    - kuber
  image:
    name: bitnami/kubectl
    entrypoint: [ "" ]
  script:
    - echo "$KUBERGOV_CONFIG" | base64 -d >.config
    - kubectl rollout restart deployment ministers --kubeconfig .config --namespace connect
  only:
    - develop


node-build-Prod:
  stage: build
  tags: 
    - master1
  image: node:14.17.2-alpine3.13
  artifacts:
    expire_in: 4h
    paths:
      - build/
  cache:
   key: ${CI_JOB_I}
   paths:
    - node_modules/
    - public/
  script:
    - echo 'nameserver 8.8.8.8' > /etc/resolv.conf
    - npm version
    - CI=false yarn install
    - CI=false yarn run build:production
  only:
    - master

dockerize-Prod:
  stage: dockerize
  tags: 
    - master1
  image: buildah/buildah
  dependencies:
    - node-build-Prod
  script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.vaslapp.com
    - buildah build-using-dockerfile -t registry.vaslapp.com/docker/ministers:latest .
    - buildah push registry.vaslapp.com/docker/ministers:latest
  only:
    - master


rollout-Prod:
  stage: rollout
  tags:
    - omid-prod
  image:
    name: bitnami/kubectl
    entrypoint: [ "" ]
  script:
    - echo "$KUBERBOH_CONFIG" | base64 -d >.config
    - kubectl rollout restart deployment ministers --kubeconfig .config --namespace connect
  when: manual