export enum ActionType {
    FETCH_GUILD_BRIEF = "FETCH_GUILDBRIEF",
    FETCH_GUILD_BRIEF_SUCCESS = "FETCH_GUILDBRIEF_SUCCESS",
    FETCH_GUILD_BRIEF_ERROR = "FETCH_GUILDBRIEF_ERROR",

    DELETE_GUILD = "DELETE_GUILD",
    CREATE_GUILD = "CREATE_GUILD",

    FETCH_GUILDINFO = "FETCH_GUILDINFO",
    FETCH_GUILDINFO_SUCCESS = "FETCH_GUILDINFO_SUCCESS",
    FETCH_GUILDINFO_ERROR = "FETCH_GUILDINFO_ERROR",

    UPDATE_EMPLOYEE_HEALTH_STATUS = "UPDATE_EMPLOYEE_HEALTH_STATUS",

    FETCH_GUILD_MESSAGES = "FETCH_GUILD_MESSAGES",
    FETCH_GUILD_MESSAGES_SUCCESS = "FETCH_GUILD_MESSAGES_SUCCESS",
    FETCH_GUILD_MESSAGES_ERROR = "FETCH_GUILD_MESSAGES_ERROR",

    FETCH_ZAERIN = "FETCH_ZAERIN",
    FETCH_ZAERIN_SUCCESS = "FETCH_ZAERIN_SUCCESS",
    FETCH_ZAERIN_ERROR = "FETCH_ZAERIN_ERROR",


    ADD_TOTAL_MEMBERS_EMPLOYEES = "ADD_TOTAL_MEMBERS_EMPLOYEES",
    ADD_TOTAL_MEMBERS_STUDENTS = "ADD_TOTAL_MEMBERS_STUDENTS",
    ADD_TOTAL_MEMBERS_EMPLOYE = "ADD_TOTAL_MEMBERS_EMPLOYE"
}