export const mokebList = [
  {
    name: 'لبیک یا حسین (ع)',
    location: 'مرز مهران',
    capacity: '34',
    type: 'اسکان و تغذیه',
    owner: 'وزارت کشور',
    managerName: 'نگین آساد',
  },
  {
    name: 'امام رضا (ع)',
    location: 'عمود ۴۲۳',
    capacity: '138',
    type: 'درمان',
    owner: 'وزارت بهداشت ',
    managerName: 'محمد علی مدنی',
  },
  {
    name: 'چهارده معصوم (ع)',
    location: 'عمود ۱۱۲۰',
    capacity: '102',
    type: 'اسکان',
    owner: 'صدا و سیما',
    managerName: 'محمد فرحزادی',
  },
  {
    name: 'قمر بنی هاشم (ع)',
    location: 'جنب خیمه گاه',
    type: 'میان وعده',
    capacity: '89',
    owner: 'صدا و سیما',
    managerName: 'مینا غلامی',
  },
  {
    name: 'بیک یا ثارالله',
    location: 'میدان پرچم',
    capacity: '46',
    type: 'تغذیه',
    owner: 'وزارت بهداشت',
    managerName: 'شادی کرباسی',
  },
  {
    name: 'شهدای گمنام ',
    location: 'صحن الزهرا (س)',
    capacity: '74',
    type: 'درمان',
    owner: 'وزارت بهداشت ',
    managerName: 'محمد علی مدنی',
  },
];
export const redHelalList = [
  {
    name: 'هتل النبا',
    baseCode: '5743',
    capacity: '53',
    providedServicesCount: '10',
    location: 'کربلا معلی',
    managerName: 'زهرا تقی زاده',
  },
  {
    name: 'صحن حضرت زهرا (س)',
    baseCode: '2467',
    capacity: '247',
    providedServicesCount: '5',
    location: 'درمانگاه مسیر نجف به کربلا',
    managerName: 'علی مرادی',
  },
  {
    name: 'یلدا الاولیا',
    baseCode: '3436',
    capacity: '436',
    providedServicesCount: '6',
    location: 'کاظمین',
    managerName: 'عباس محمد پور',
  },
  {
    name: 'عمود ۷۷۷',
    baseCode: '1478',
    capacity: '14',
    providedServicesCount: '5',
    location: 'نجف اشرف',
    managerName: 'مجتبی شیرازی',
  },

  {
    name: 'پایگاه کمیل',
    baseCode: '3456',
    capacity: '33',
    providedServicesCount: '20',
    location: 'سامرا و سید محمد ',
    managerName: 'محمد علی مدنی',
  },
];
export const pilgrimsCity = [
  {
    city: 'تهران',
    pilgrimsCount: '5000',
    womenPercentage: '40',
    menPercentage: '60',
    visasIssuedCount: '5100',
    vaccinePercentage: '90',
    firestDosesPercentage: '20',
    secondDosesPercentage: '',
    thirdDosesPercentage: '',
  },
  {
    city: 'مشهد',
    pilgrimsCount: '1500',
    womenPercentage: '40',
    menPercentage: '60',
    visasIssuedCount: '1600',
    vaccinePercentage: '90',
    firestDosesPercentage: '10',
    secondDosesPercentage: '35',
    thirdDosesPercentage: '45',
  },
  {
    city: 'قم',
    pilgrimsCount: '1200',
    womenPercentage: '45',
    menPercentage: '55',
    visasIssuedCount: '1300',
    vaccinePercentage: '92',
    firestDosesPercentage: '10',
    secondDosesPercentage: '32',
    thirdDosesPercentage: '50',
  },
  {
    city: 'خوزستان',
    pilgrimsCount: '1000',
    womenPercentage: '30',
    menPercentage: '70',
    visasIssuedCount: '1100',
    vaccinePercentage: '90',
    firestDosesPercentage: '15',
    secondDosesPercentage: '35',
    thirdDosesPercentage: '40',
  },
  {
    city: 'تبریز',
    pilgrimsCount: '200',
    womenPercentage: '35',
    menPercentage: '65',
    visasIssuedCount: '300',
    vaccinePercentage: '90',
    firestDosesPercentage: '20',
    secondDosesPercentage: '20',
    thirdDosesPercentage: '50',
  },
];
export const pilgrimsCountries = [
  {
    country: 'پاکستان',
    pilgrimsCount: '500',
    womenPercentage: '45',
    menPercentage: '45',
    pilgrimsTototalPercentage: '5',
  },
  {
    country: 'افغانستان',
    pilgrimsCount: '100',
    womenPercentage: '30',
    menPercentage: '70',
    pilgrimsTototalPercentage: '1',
  },
  {
    country: 'ترکیه',
    pilgrimsCount: '400',
    womenPercentage: '40',
    menPercentage: '60',
    pilgrimsTototalPercentage: '4',
  },
];
export const pilgrimsList = [
  {
    pilgrimName: null,
    pilgrimNationalId: null,
    exitBorder: null,
    dateOfDispatch: null,
    returnDate: null,
    SendingProvince: null,
    pilgrimMobileNumber: null,
  },

  {
    pilgrimName: 'نگین آساده',
    pilgrimNationalId: '25366588996',
    exitBorder: 'مرز مهران',
    dateOfDispatch: '2022.11.12',
    returnDate: '2022.11.12',
    SendingProvince: 'تهران',
    pilgrimMobileNumber: '02356987566',
  },
];

export const abroadData = [
  {
    bordearnName: 'مهران',
    inportCount: 6000,
    exportCount: 5000,
    waitingVisaCheck: 50,
    AverageDailyEntryRate: 600,
    AverageDailyOutRate: 500,
    PercentageShareEachBorderVisaFromPilgrims: 55,
  },
  {
    bordearnName: 'شلمچه',
    inportCount: 2000,
    exportCount: 3000,
    waitingVisaCheck: 100,
    AverageDailyEntryRate: 200,
    AverageDailyOutRate: 300,
    PercentageShareEachBorderVisaFromPilgrims: 25,
  },
  {
    bordearnName: 'چزابه',
    inportCount: 1200,
    exportCount: 1500,
    waitingVisaCheck: 100,
    AverageDailyEntryRate: 120,
    AverageDailyOutRate: 150,
    PercentageShareEachBorderVisaFromPilgrims: 14,
  },
  {
    bordearnName: 'خسروی',
    inportCount: 800,
    exportCount: 500,
    waitingVisaCheck: 50,
    AverageDailyEntryRate: 80,
    AverageDailyOutRate: 50,
    PercentageShareEachBorderVisaFromPilgrims: 7,
  },
];
export const axisData = [
  {
    name: 'ایلام- مهران',
    climate: 'بارانی',
    avaragePilgrim: 500,
    trafficStatus: 'سنگین',
    axisStatus: 'غیر مسدود',
  },
  {
    name: 'قصر شیرین - مرز خسروی',
    climate: 'آفتابی',
    avaragePilgrim: 600,
    trafficStatus: 'نیمه سنگین',
    axisStatus: 'غیر مسدود',
  },
  {
    name: 'کرمانشاه - اسلام آباد ',
    climate: 'طوفانی',
    avaragePilgrim: 700,
    trafficStatus: 'نیمه سنگین',
    axisStatus: 'غیر مسدود',
  },
];
